name: Feature request
description: 提交功能請求
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        感謝您的貢獻！請按照以下格式填寫您的功能請求。這將有助於更好地管理和追蹤功能需求。

  - type: dropdown
    id: feature_type
    attributes:
      label: 功能類型
      description: 請選擇功能請求的類型。
      options:
        - 新功能
        - 更新功能
        - 優化功能
        - 文件
    validations:
      required: true

  - type: textarea
    id: feature_description
    attributes:
      label: 功能描述
      description: 請具體說明您想要的功能以及它將解決的問題。
      placeholder: 請輸入詳細的描述
    validations:
      required: true

  - type: input
    id: use_case
    attributes:
      label: 使用情境
      description: 說明此功能將如何被使用，並舉例說明可能的應用情境。
      placeholder: 使用此功能的具體情境

  - type: dropdown
    id: scope_of_impact
    attributes:
      label: 影響範圍
      description: 請選擇此功能的影響範圍。
      options:
        - 小範圍修改
        - 模組範圍變更
        - 全系統影響

  - type: checkboxes
    id: alternatives_considered
    attributes:
      label: 其他方案
      description: 您是否考慮過其他替代方案？請選擇並加以說明。
      options:
        - label: 已考慮
        - label: 尚未考慮
